# Generated by Django 5.0.6 on 2024-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(max_length=30, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('studentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField(max_length=30, null=True, unique=True)),
                ('course', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=400, unique=True)),
                ('phone_number', models.IntegerField(max_length=15, null=True)),
            ],
        ),
    ]
