# Generated by Django 5.0.6 on 2024-06-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='student_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
