# Generated by Django 5.0.6 on 2024-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_student_info_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='phone_number',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
