# Generated by Django 5.0.6 on 2024-06-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_alter_student_info_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='phone_number',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
    ]
